layout_spectrum: 0.7689713
description: tragédia dançante
name: Shampoo
title: SHAMPOO
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0
color:
  brandStrength: 0.4787771166302264
  lightness: 0.3971332
  saturation: 0.1036794
  rhythmicContrast: 1
  brandColors:
    - '#E9008C'
    - '#1FA553'
    - '#FFFFFF'
    - '#231F20'
    - '#FDF02D'
